export const ProductsDate = [
    {
        brand:"HP",
        title:"Victus 16 Gaming Laptop",
        specs:"Intel Core i5 Processor, RTX 3050, 16GB RAM, 512GB SSD, 16.1\"",
        price:"699",
        color:"Mica Silver",
        image:"DB/DB-Imgs/victus.webp",
        image1:"DB/DB-Imgs/victus1.webp"
    },
    {
        brand:"Apple",
        title:"Apple MacBook Air",
        specs:"2020, 13.3\" Retina Display, M1 Processor, 8GB RAM, 256GB SSD",
        price:"829",
        color:"Space Grey",
        image:"DB/DB-Imgs/macbookair.webp",
        image1:"DB/DB-Imgs/macbookair1.webp"
    },
    {
        brand:"ASUS",
        title:"TUF A15 Gaming Laptop",
        specs:"Intel Core i7 Processor, 16GB RAM, RTX 4050, 512GB SSD, 15.6\" Full HD",
        price:"999",
        color:"Arctic Grey",
        image:"DB/DB-Imgs/tufa15.webp",
        image1:"DB/DB-Imgs/tufa151.webp"
    },
    {
        brand:"Lenovo",
        title:"LOQ 15IRH8 Gaming Laptop",
        specs:"Intel Core i5 Processor, 16GB RAM, RTX 4050, 512GB SSD, 15.6\" Full HD",
        price:"849.99",
        color:"Storm Grey",
        image:"DB/DB-Imgs/loq.webp",
        image1:"DB/DB-Imgs/loq1.webp"
    },
    // {
    //     brand:"HP",
    //     title:"OMEN 16 Gaming Laptop",
    //     specs:"AMD Ryzen 7 Processor, RTX 4050, 16GB RAM, 512GB SSD, 16.1\"",
    //     price:"1099",
    //     color:"Black",
    //     image:"DB/DB-Imgs/omen.webp",
    //     image1:"DB/DB-Imgs/omen1.webp"
    // },
    // {
    //     brand:"Samsung",
    //     title:"Galaxy Book3 Laptop",
    //     specs:"Intel Core i5 Processor, 8GB RAM, 256GB SSD, 15.6\" Full HD",
    //     price:"749",
    //     color:"Graphite",
    //     image:"DB/DB-Imgs/book3.webp",
    //     image1:"DB/DB-Imgs/book31.webp"
    // }

]


export const CablesData = [
    {
        brand:"Mouse",
        title:"Mouse Wireless",
        price:"849.99",
        color:"Storm Grey",
        image:"DB/DB-Imgs/mouse1.jpg",
    },
    {
        brand:"Cable HDMI",
        title:"Cable",
        price:"849.99",
        color:"Storm Grey",
        image:"DB/DB-Imgs/cable.jpeg",
    },
    {
        brand:"Stand Laptop",
        title:"Mouse Wireless",
        price:"849.99",
        color:"Storm Grey",
        image:"DB/DB-Imgs/stand.jpg",
    },
    {
        brand:"Ethernet Cable",
        title:"Mouse Wireless",
        price:"849.99",
        color:"Storm Grey",
        image:"DB/DB-Imgs/cable1.webp",
    },
    {
        brand:"Keyboard",
        title:"Mouse Wireless",
        price:"849.99",
        color:"Storm Grey",
        image:"DB/DB-Imgs/key.jpeg",
    },

]


export const ProductElement = [
    {
        id:1,
        brand:"HP",
        title:"Victus 16 Gaming Laptop",
        specs:"Intel Core i5 Processor, RTX 3050, 16GB RAM, 512GB SSD, 16.1\"",
        price:"699",
        color:"Mica Silver",
        qty:"0",
        image:"DB/DB-Imgs/victus.webp",
        image1:"DB/DB-Imgs/victus1.webp",
    },
    {
        id:2,
        brand:"Apple",
        title:"Apple MacBook Air",
        specs:"2020, 13.3\" Liquid Retina Display, M1 Processor, 8GB RAM, 256GB SSD",
        price:"829",
        color:"Space Grey",
        qty:"0",
        image:"DB/DB-Imgs/macbookair.webp",
        image1:"DB/DB-Imgs/macbookair1.webp",
    },
    {
        id:3,
        brand:"ASUS",
        title:"TUF A15 Gaming Laptop",
        specs:"Intel Core i7 Processor, 16GB RAM, RTX 4050, 512GB SSD, 15.6\" Full HD",
        price:"999",
        color:"Arctic Grey",
        qty:"0",
        image:"DB/DB-Imgs/tufa15.webp",
        image1:"DB/DB-Imgs/tufa151.webp",
    },
    {
        id:4,
        brand:"ASUS",
        title:"ROG Strix SCAR 16",
        specs:"Intel Core i9 Processor, 32GB RAM, RTX 4080, 2TB SSD, 16\" QHD+",
        price:"2849",
        color:"Black",
        qty:"0",
        image:"DB/DB-Imgs/strixscar16.webp",
        image1:"DB/DB-Imgs/strixscar161.webp",
    },
    {
        id:5,
        brand:"Microsoft",
        title:"Surface Studio 2 Laptop",
        specs:"Intel Core i7, 32GB RAM, 1TB SSD, 14.4\" PixelSense Display",
        price:"2652",
        color:"Platinum",
        qty:"0",
        image:"DB/DB-Imgs/surfacestudio.webp",
        image1:"DB/DB-Imgs/surfacestudio1.webp",
    },
    {
        id:6,
        brand:"Apple",
        title:"Apple MacBook Pro",
        specs:"2023, 14\", M3 Max Processor, 36GB RAM, 1TB SSD",
        price:"3099",
        color:"Silver",
        qty:"0",
        image:"DB/DB-Imgs/macbookpro.jpg",
        image1:"DB/DB-Imgs/macbookpro1.webp",
    },
    {
        id:7,
        brand:"Samsung",
        title:"Galaxy Book3 Laptop",
        specs:"Intel Core i5 Processor, 8GB RAM, 256GB SSD, 15.6\" Full HD",
        price:"749",
        color:"Graphite",
        qty:"0",
        image:"DB/DB-Imgs/book3.webp",
        image1:"DB/DB-Imgs/book31.webp",
    },
    {
        id:8,
        brand:"Razer",
        title:"Blade 14 Gaming Laptop",
        specs:"AMD Ryzen 9, 16GB RAM, RTX 3080 Ti, 1TB SSD, 14\" QHD",
        price:"2229",
        color:"Black",
        qty:"0",
        image:"DB/DB-Imgs/blade14.webp",
        image1:"DB/DB-Imgs/blade141.webp",
    },
    {
        id:9,
        brand:"Lenovo",
        title:"LOQ 15IRH8 Gaming Laptop",
        specs:"Intel Core i5, 16GB RAM, RTX 4050, 512GB SSD, 15.6\" Full HD",
        price:"849",
        color:"Storm Grey",
        qty:"0",
        image:"DB/DB-Imgs/loq.webp",
        image1:"DB/DB-Imgs/loq1.webp",
    },
    {
        id:10,
        brand:"HP",
        title:"OMEN 16 Gaming Laptop",
        specs:"AMD Ryzen 7 Processor, RTX 4050, 16GB RAM, 512GB SSD, 16.1\"",
        price:"1099",
        color:"Black",
        qty:"0",
        image:"DB/DB-Imgs/omen.webp",
        image1:"DB/DB-Imgs/omen1.webp",
    },
    {
        id:11,
        brand:"ASUS",
        title:"VivoBook Pro 16X Laptop",
        specs:"Intel Core i9 Processor, 32GB RAM, RTX 4070, 1TB SSD, 16\" OLED 3.2K",
        price:"2499",
        color:"Silver",
        qty:"0",
        image:"DB/DB-Imgs/vivobook.webp",
        image1:"DB/DB-Imgs/vivobook1.webp",
    },
    {
        id:12,
        brand:"MSI",
        title:"Raider GE68HX",
        specs:"Intel Core i9 Processor, 16GB RAM, RTX 4070, 1TB SSD, 16\" UHD+",
        price:"2199",
        color:"Core Black",
        qty:"0",
        image:"DB/DB-Imgs/raider.webp",
        image1:"DB/DB-Imgs/raider1.webp",
    },
    {
        id:13,
        brand:"Samsung",
        title:"Galaxy Book4 Ultra Laptop",
        specs:"Intel Core Ultra 9, 32GB RAM, 1TB SSD, RTX 4070, 16\" 3K Touch Screen",
        price:"3149",
        color:"Moonstone Grey",
        qty:"0",
        image:"DB/DB-Imgs/book4.webp",
        image1:"DB/DB-Imgs/book41.webp",
    },
    {
        id:14,
        brand:"Acer",
        title:"Nitro AN17-51 Gaming Laptop",
        specs:"Intel Core i7 Processor, 16GB RAM, RTX 4060, 1TB SSD, 17.3\" QHD",
        price:"1519",
        color:"Black",
        qty:"0",
        image:"DB/DB-Imgs/nitro.webp",
        image1:"DB/DB-Imgs/nitro1.webp",
    },
    {
        id:15,
        brand:"HP",
        title:"Pavilion 15-eh1024na Laptop",
        specs:"AMD Ryzen 5 Processor, 8GB RAM, 512GB SSD, 15.6\" Full HD Touchscreen",
        price:"499",
        color:"Silver",
        qty:"0",
        image:"DB/DB-Imgs/pavilion.webp",
        image1:"DB/DB-Imgs/pavilion1.webp",
    },
    {
        id:16,
        brand:"Asus",
        title:"ROG Flow Z13 Convertible Laptop",
        specs:"Intel Core i9 Processor, RTX 4070, 32GB RAM, 1TB SSD, 13.4\" WQUXGA Touch Screen",
        price:"2699",
        color:"Black",
        qty:"0",
        image:"DB/DB-Imgs/rogflow.webp",
        image1:"DB/DB-Imgs/rogflow1.webp",
    },
    {
        id:17,
        brand:"Acer",
        title:"Swift 3 Laptop",
        specs:"AMD Ryzen 7 Processor, 8GB RAM, 1TB SSD, 14\" Full HD",
        price:"799",
        color:"Silver",
        qty:"0",
        image:"DB/DB-Imgs/swift3.webp",
        image1:"DB/DB-Imgs/swift31.webp",
    },
    {
        id:18,
        brand:"ASUS",
        title:"ZenBook 14 Laptop",
        specs:"Intel Core i5 Processor, 8GB RAM, 512GB SSD, 14\" LED",
        price:"529",
        color:"Blue",
        qty:"0",
        image:"DB/DB-Imgs/zenbook.webp",
        image1:"DB/DB-Imgs/zenbook1.webp",
    },
    {
        id:19,
        brand:"Lenovo",
        title:"IdeaPad Slim 5i Laptop",
        specs:"Intel i5 Core Processor, 16GB RAM, 512GB SSD, 16\" WUXGA",
        price:"749",
        color:"Abyss Blue",
        qty:"0",
        image:"DB/DB-Imgs/ideapad5i.webp",
        image1:"DB/DB-Imgs/ideapad5i1.webp",
    },
    {
        id:20,
        brand:"Apple",
        title:"Apple MacBook Air",
        specs:"2023 15.3\", M2 Processor, 16GB RAM, 512GB SSD",
        price:"1699",
        color:"Silver",
        qty:"0",
        image:"DB/DB-Imgs/macbookair2.webp",
        image1:"DB/DB-Imgs/macbookair21.webp",
    },
    {
        id:21,
        brand:"Razer",
        title:"Blade 17 Gaming Laptop",
        specs:"Intel Core i7 Processor, 16GB RAM, RTX 3070 Ti, 1TB SSD, 17.3\" QHD",
        price:"1649",
        color:"Black",
        qty:"0",
        image:"DB/DB-Imgs/blade17.webp",
        image1:"DB/DB-Imgs/blade171.jpg",
    },
    {
        id:22,
        brand:"Microsoft",
        title:"Surface Laptop Go 3",
        specs:"Intel Core i5 Processor, 8GB RAM, 256GB SSD, 12.4\" PixelSense Touchscreen",
        price:"699",
        color:"Platinum",
        qty:"0",
        image:"DB/DB-Imgs/surfacelaptop.webp",
        image1:"DB/DB-Imgs/surfacelaptop1.webp",
    },
    {
        id:23,
        brand:"HP",
        title:"Pavilion 15-dk2029na Gaming Laptop",
        specs:"Intel Core i5 Processor, 8GB RAM, 512GB SSD, 15.6\" Full HD",
        price:"799",
        color:"Shadow Black",
        qty:"0",
        image:"DB/DB-Imgs/pavillion15.webp",
        image1:"DB/DB-Imgs/pavillion151.webp",
    },
    {
        id:24,
        brand:"Lenovo",
        title:"IdeaPad Duet 3",
        specs:"Qualcomm Snapdragon Processor, 8GB RAM, 128GB eMMC, 11\" 2K",
        price:"399",
        color:"Storm Grey",
        qty:"0",
        image:"DB/DB-Imgs/duet3.webp",
        image1:"DB/DB-Imgs/duet31.webp",
    },
    {
        id:25,
        brand:"Lenovo",
        title:"IdeaPad 3i Laptop",
        specs:"Intel Core i5 Processor, 16GB RAM, 512GB SSD, 15.6\" Full HD",
        price:"579",
        color:"Abyss Blue",
        qty:"0",
        image:"DB/DB-Imgs/pavilion.webp",
        image1:"DB/DB-Imgs/pavilion1.webp",
    },
    {
        id:26,
        brand:"Apple",
        title:"Apple MacBook Air",
        specs:"2022 13.6\" Liquid Retina Display, M2 Processor, 8GB RAM, 256GB",
        price:"1099",
        color:"Space Grey",
        qty:"0",
        image:"DB/DB-Imgs/macbookair3.webp",
        image1:"DB/DB-Imgs/macbookair31.webp",
    },
    {
        id:27,
        brand:"HP",
        title:"ENVY x360 Convertible",
        specs:"Intel Core i7, 16GB RAM, 512GB SSD, 13.3\" Full HD+ Touchscreen",
        price:"849",
        color:"Silver",
        qty:"0",
        image:"DB/DB-Imgs/envy.webp",
        image1:"DB/DB-Imgs/envy1.webp",
    },
]


export const HomeData = [
    {
        name : "Swift 3 Laptop",
        brand :"Hp",
        imgLink : "DB/DB-Imgs/home1.png"
    },
    {
        name : "Apple MacBook Air",
        brand :"Apple",
        imgLink : "DB/DB-Imgs/home2.png"
    },
    {
        name : "IdeaPad Duet 3",
        brand :"Hp",
        imgLink : "DB/DB-Imgs/home3.png"
    },
]